export const SET_SEO_TITLE = 'app/general/seo/SET_SEO_TITLE'
export const SET_SEO_DESC = 'app/general/seo/SET_SEO_DESC'
export const SET_SEO_TAGS = 'app/general/seo/SET_SEO_TAGS'
export const GET_SEO_DETAILS = 'app/general/seo/GET_SEO_DETAILS'
export const SET_SEO_DETAILS = 'app/general/seo/SET_SEO_DETAILS'
export const SET_LOADING = 'app/general/seo/SET_LOADING'
export const SET_ERROR_MESSAGE = 'app/general/seo/SET_ERROR_MESSAGE'
