export const GET_ABOUT_US = "GET_ABOUT_US"
export const SET_ABOUT_US = "SET_ABOUT_US"

export const SEND_ABOUT_US = "SEND_ABOUT_US"

export const SET_ABOUT_US_EMAIL = "SET_ABOUT_US_EMAIL"
export const SET_ABOUT_US_CONTACT = "SET_ABOUT_US_CONTACT"
export const SET_ABOUT_US_DESCRIPTION = "SET_ABOUT_US_DESCRIPTION"

export const GET_ABOUT_US_STATUS = "GET_ABOUT_US_STATUS"
export const SET_ABOUT_US_STATUS = "SET_ABOUT_US_STATUS"
