export const SET_PAGE_INDEX = 'app/general/marketing&branding/push-coupons/SET_PAGE_INDEX'
export const SET_LOADING = 'app/general/marketing&branding/push-coupons/SET_LOADING'

export const APPEND_COUPON = 'app/general/marketing&branding/coupons/APPEND_COUPON'
export const SET_PAGE_INDEX_COUPONS = 'app/general/marketing&branding/push-coupons/SET_PAGE_INDEX_COUPON'
export const GET_TOTAL_COUPONS = 'app/general/marketing&branding/push-coupons/GET_TOTAL_COUPONS'
export const SET_TOTAL_COUPONS = 'app/general/marketing&branding/push-coupons/SET_TOTAL_COUPONS'
export const DELETE_COUPONS_IN_DB = 'app/general/marketing&branding/push-coupons/DELETE_COUPONS_IN_DB'
export const DELETE_COUPONS = 'app/general/marketing&branding/push-coupons/DELETE_COUPONS'
export const RESET_COUPONS = 'app/general/marketing&branding/push-coupons/RESET_COUPONS'
export const GET_COUPONS = 'app/general/marketing&branding/push-coupons/GET_COUPONS'
export const SET_COUPONS = 'app/general/marketing&branding/push-coupons/SET_COUPONS'
export const SET_LOADING_COUPONS = 'app/general/marketing&branding/push-coupons/SET_LOADING_COUPONS'
export const GET_ALL_COUPON_TYPES = 'app/general/marketing&branding/push-coupons/GET_ALL_COUPON_TYPES'
export const SET_ALL_COUPON_TYPES = 'app/general/marketing&branding/push-coupons/SET_ALL_COUPON_TYPES'
export const CREATE_COUPONS = 'app/general/marketing&branding/push_coupons/SET_COUPONS'
export const UPDATE_COUPONS = 'app/general/marketing&branding/push_coupons/UPDATE_COUPONS'
export const SET_COUPONS_STATUS = 'app/general/marketing&branding/push_coupons/SET_COUPONS_STATUS'
