export const SET_BANK_NAME = 'app/general/bank-details/SET_BANK_NAME'
export const SET_ACCOUNT_NAME = 'app/general/bank-details/SET_ACCOUNT_NAME'
export const SET_ACCOUNT_NO = 'app/general/bank-details/SET_ACCOUNT_NO'
export const SET_IFSC_CODE = 'app/general/bank-details/SET_IFSC_CODE'
export const SET_BRANCH = 'app/general/bank-details/SET_BRANCH'
export const GET_BANK_DETAILS = 'app/general/bank-details/GET_BANK_DETAILS'
export const SET_BANK_DETAILS = 'app/general/bank-details/SET_BANK_DETAILS'
