export const GET_PAST_ORDERS = 'app/orders/GET_PAST_ORDERS'
export const SET_PAST_ORDERS = 'app/orders/SET_PAST_ORDERS'
export const SEND_REPORT = 'app/orders/SEND_REPORT'
export const SET_CANCELLED_ORDERS = 'app/orders/SET_CANCELLED_ORDERS'
export const SET_DELIVERED_ORDERS = 'app/orders/SET_DELIVERED_ORDERS'
export const SET_HAS_MORE = 'app/orders/SET_HAS_MORE'
export const SET_LOADING = 'app/orders/SET_LOADING'