export const GET_CREDIT_NUMBERS = "GET_CREDIT_NUMBERS"
export const SET_CREDIT_NUMBERS = "SET_CREDIT_NUMBERS"
export const SET_CREDIT_PRICING = "SET_CREDIT_PRICING"

export const SET_CREDIT_TYPE = "SET_CREDIT_TYPE"
export const SET_CREDIT_AMT = "SET_CREDIT_AMT"
export const SET_NO_OF_CREDIT = "SET_NO_OF_CREDIT"