/*
 *
 * CustomizePage constants
 *
 */

export const CHANGE_REST_NAME = 'CHANGE_REST_NAME'
export const APPLY_PRIMARY_COLOR = 'APPLY_PRIMARY_COLOR'
export const LOAD_COVER_PIC = 'LOAD_COVER_PIC'
export const UPLOAD_COVER_PIC = 'UPLOAD_COVER_PIC'
export const LOAD_LOGO_IMG = 'LOAD_LOGO_IMG'
export const UPLOAD_LOGO_IMG = 'UPLOAD_LOGO_IMG'
export const TOGGLE_PREVIEW_STATE = 'TOGGLE_PREVIEW_STATE'
export const SAVE_CUSTOM_CONFIG = 'SAVE_CUSTOM_CONFIG'
export const CHANGE_ITEM_SECTION_LAYOUT = 'CHANGE_ITEM_SECTION_LAYOUT'
export const SAVE_DISPLAY_SETTINGS = 'customize/SAVE_DISPLAY_SETTINGS'
export const SAVE_BANNER_TO_DB = 'customize/SAVE_BANNER_TO_DB'
